spring:
  datasource:
    control:
      url: jdbc:sqlite:control.db
      driver-class-name: org.sqlite.JDBC
  flyway:
    control:
      jdbcUrl: jdbc:sqlite:control.db
      driverClassName: org.sqlite.JDBC
  security:
    user:
      name: admin
      password: admin
app:
  version: v1
  adapter: database